language: node_js
node_js:
- '8'
cache:
  directories:
    - node_modules
    - rest-server/node_modules
    - socket-server/node_modules
    - services/coderunner-service/node_modules
services: postgresql
before_install:
  - psql -c "CREATE DATABASE codesling;" -U postgres
  - psql -c "CREATE USER root WITH SUPERUSER PASSWORD '';" -U postgres
install:
  - yarn
  - yarn buildEnv
  - yarn setup:rest-server
  - yarn setup:socket-server
  - yarn setup:services/coderunner-service
  - yarn db:setup:rest-server
script:
  - yarn start &
  - find . -type d -name "*node_modules*" -prune -o -type f -print | zip latest-api.zip -@
  - mkdir -p upload_dir
  - mv latest-api.zip upload_dir/latest-api.zip

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: upload_dir
  skip_cleanup: true
  on: &2
    repo: LegacyDreamTeam/codesling.io-api
    branch: travis
  bucket: legacy-s3
  region: us-west-1
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: legacy-s3
  key: latest-api.zip
  bundle_type: zip
  application: legacy
  deployment_group: legacy-group
  region: us-west-1
  on: *2
